services:
  node-backend:
    build:
      context: .
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    command: npm run dev

  mongo:
    ports:
      - "27017:27017"

  redis:
    ports:
      - "6379:6379"