services:
  node-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_USERNAME=oraion
      - MONGO_PASSWORD=iB2R9uoLn2uYe3ES
    volumes:
      - ./:/app:ro
      - /app/node_modules
    
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=oraion
      - MONGO_INITDB_ROOT_PASSWORD=iB2R9uoLn2uYe3ES
    volumes:
      - mongo-genie:/data/db

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

volumes:
  mongo-genie: